language: python

sudo: false
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=flake8
  - TOXENV=cov

install:
  - travis_retry pip install tox coveralls

script:
  - tox

after_success:
  - coveralls
